LANGSMITH_API_KEY: "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"
LANGCHAIN_TRACING_V2: "true"
LANGCHAIN_ENDPOINT: "https://api.smith.langchain.com"
LANGCHAIN_PROJECT: "CDC"
OPENAI_API_KEY: "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"